<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.2.4" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\TWD.NotCasino.Api.Core\TWD.NotCasino.Api.Core.csproj" />
    <ProjectReference Include="..\..\Core\TWD.NotCasino.Application\TWD.NotCasino.Application.csproj" />
    <ProjectReference Include="..\..\Core\TWD.NotCasino.Core\TWD.NotCasino.Core.csproj" />
    <ProjectReference Include="..\TWD.NotCasino.Base\TWD.NotCasino.Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
  </ItemGroup>

</Project>
