// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TWD.NotCasino.Domain.Core;

#nullable disable

namespace TWD.NotCasino.Domain.Base.Postgres.Migrations
{
    [DbContext(typeof(NotCasinoContext))]
    [Migration("20250826211654_AddRoleFopUser")]
    partial class AddRoleFopUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TWD.NotCasino.Core.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Id записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Coins")
                        .HasColumnType("numeric")
                        .HasComment("Текущее количество монет");

                    b.Property<decimal>("LosesMoneyCount")
                        .HasColumnType("numeric")
                        .HasComment("Общее количество проигранных монет");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("Id пользователя");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Accounts", t =>
                        {
                            t.HasComment("Аккаунты пользователя");
                        });
                });

            modelBuilder.Entity("TWD.NotCasino.Core.Entities.GameLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Id записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Bet")
                        .HasColumnType("integer")
                        .HasComment("Ставка");

                    b.Property<string>("GameData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Доп информация об игре");

                    b.Property<byte>("GameType")
                        .HasColumnType("smallint")
                        .HasComment("Тип игры");

                    b.Property<long>("ReloadAccountId")
                        .HasColumnType("bigint")
                        .HasComment("Id обновления аккаунта");

                    b.Property<byte>("Result")
                        .HasColumnType("smallint")
                        .HasComment("Результат игры");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasComment("Id сервера");

                    b.Property<int>("Win")
                        .HasColumnType("integer")
                        .HasComment("Выигрыш");

                    b.HasKey("Id");

                    b.HasIndex("ReloadAccountId");

                    b.HasIndex("ServerId");

                    b.ToTable("GameLogs", t =>
                        {
                            t.HasComment("Логи игр");
                        });
                });

            modelBuilder.Entity("TWD.NotCasino.Core.Entities.GameSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Id записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("GameSettingType")
                        .HasColumnType("smallint")
                        .HasComment("Тип настройки");

                    b.Property<byte>("GameType")
                        .HasColumnType("smallint")
                        .HasComment("Тип игры");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasComment("Id сервера");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Значение настройки");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("GameSettings", t =>
                        {
                            t.HasComment("Настройки игр");
                        });
                });

            modelBuilder.Entity("TWD.NotCasino.Core.Entities.ReloadAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Id записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата обновления аккаунта");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("Id пользователя");

                    b.HasKey("Id");

                    b.HasIndex("CreateDate");

                    b.HasIndex("UserId");

                    b.ToTable("ReloadAccounts", t =>
                        {
                            t.HasComment("Обновления аккаунтов");
                        });
                });

            modelBuilder.Entity("TWD.NotCasino.Core.Entities.Server", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Id записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Coins")
                        .HasColumnType("numeric")
                        .HasComment("Количество монет");

                    b.Property<byte>("ServerName")
                        .HasColumnType("smallint")
                        .HasComment("Сервер");

                    b.HasKey("Id");

                    b.ToTable("Servers", t =>
                        {
                            t.HasComment("Настройки серверов");
                        });
                });

            modelBuilder.Entity("TWD.NotCasino.Core.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Id записи");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Почта");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasComment("Заблокирован ли");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean")
                        .HasComment("Удалён ли");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Логин");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Никнейм");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Хеш пароль");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Users", t =>
                        {
                            t.HasComment("Пользователи");
                        });
                });

            modelBuilder.Entity("TWD.NotCasino.Core.Entities.Account", b =>
                {
                    b.HasOne("TWD.NotCasino.Core.Entities.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("TWD.NotCasino.Core.Entities.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TWD.NotCasino.Core.Entities.GameLog", b =>
                {
                    b.HasOne("TWD.NotCasino.Core.Entities.ReloadAccount", "ReloadAccount")
                        .WithMany()
                        .HasForeignKey("ReloadAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TWD.NotCasino.Core.Entities.Server", "Server")
                        .WithMany("GameLogs")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReloadAccount");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("TWD.NotCasino.Core.Entities.GameSetting", b =>
                {
                    b.HasOne("TWD.NotCasino.Core.Entities.Server", "Server")
                        .WithMany("GameSettings")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("TWD.NotCasino.Core.Entities.ReloadAccount", b =>
                {
                    b.HasOne("TWD.NotCasino.Core.Entities.User", "User")
                        .WithMany("ReloadAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TWD.NotCasino.Core.Entities.Server", b =>
                {
                    b.Navigation("GameLogs");

                    b.Navigation("GameSettings");
                });

            modelBuilder.Entity("TWD.NotCasino.Core.Entities.User", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("ReloadAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
